###Listar productos
GET http://localhost:3000/producto

###Crear producto
POST http://localhost:3000/producto
Content-Type: application/json

{
    "nombre": "Ventilador",
    "precio": "241.50",
    "stock": 10,
    "categoriaId": 1
}

###Buscar producto por ID
GET http://localhost:3000/producto/back?
